<?php

namespace App\Filament\Resources;

use App\Filament\Resources\MonitoringResultResource\Pages;
use App\Filament\Resources\MonitoringResultResource\RelationManagers;
use App\Models\MonitoringResult;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\SoftDeletingScope;

class MonitoringResultResource extends Resource
{
    protected static ?string $model = MonitoringResult::class;

    protected static ?string $navigationIcon = 'heroicon-o-chart-bar';

    protected static ?string $navigationGroup = 'Monitoring';

    protected static ?string $navigationLabel = 'Results';

    protected static ?int $navigationSort = 2;

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                // Monitoring results are read-only - generated by the monitoring system
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('website.name')
                    ->sortable()
                    ->searchable()
                    ->label('Website'),
                Tables\Columns\TextColumn::make('status')
                    ->badge()
                    ->color(fn(string $state): string => match ($state) {
                        'up' => 'success',
                        'down' => 'danger',
                        'error' => 'danger',
                        'warning' => 'warning',
                        default => 'gray',
                    })
                    ->searchable(),
                Tables\Columns\TextColumn::make('status_code')
                    ->badge()
                    ->color(fn(?int $state): string => match (true) {
                        $state >= 200 && $state < 300 => 'success',
                        $state >= 300 && $state < 400 => 'warning',
                        $state >= 400 => 'danger',
                        default => 'gray',
                    })
                    ->sortable()
                    ->label('HTTP Code'),
                Tables\Columns\TextColumn::make('response_time')
                    ->numeric()
                    ->sortable()
                    ->suffix(' ms')
                    ->color(fn(?int $state): string => match (true) {
                        $state < 1000 => 'success',
                        $state < 3000 => 'warning',
                        $state >= 3000 => 'danger',
                        default => 'gray',
                    }),
                Tables\Columns\IconColumn::make('content_changed')
                    ->boolean()
                    ->label('Content Changed'),
                Tables\Columns\ImageColumn::make('screenshot_path')
                    ->disk('public')
                    ->height(50)
                    ->width(70)
                    ->label('Screenshot')
                    ->visibility('private'),
                Tables\Columns\TextColumn::make('checked_at')
                    ->dateTime()
                    ->sortable()
                    ->since(),
                Tables\Columns\TextColumn::make('created_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                Tables\Columns\TextColumn::make('updated_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->filters([
                Tables\Filters\SelectFilter::make('website')
                    ->relationship('website', 'name')
                    ->searchable()
                    ->preload(),
                Tables\Filters\SelectFilter::make('status')
                    ->options([
                        'up' => 'Up',
                        'down' => 'Down',
                        'error' => 'Error',
                        'warning' => 'Warning',
                    ]),
                Tables\Filters\Filter::make('content_changed')
                    ->query(fn(Builder $query): Builder => $query->where('content_changed', true))
                    ->label('Content Changed'),
                Tables\Filters\Filter::make('has_screenshot')
                    ->query(fn(Builder $query): Builder => $query->whereNotNull('screenshot_path'))
                    ->label('Has Screenshot'),
                Tables\Filters\Filter::make('no_screenshot')
                    ->query(fn(Builder $query): Builder => $query->whereNull('screenshot_path'))
                    ->label('No Screenshot'),
            ])
            ->actions([
                Tables\Actions\ViewAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ])
            ->defaultSort('created_at', 'desc');
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function canCreate(): bool
    {
        return false;
    }

    public static function canEdit($record): bool
    {
        return false;
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListMonitoringResults::route('/'),
            'view' => Pages\ViewMonitoringResult::route('/{record}'),
        ];
    }
}
